openapi: 3.0.0
info:
  title: Plantation Management API
  description: API for managing estates, trees, and drone planning
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /estate:
    post:
      summary: Create an estate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                length:
                  type: integer
                width:
                  type: integer
      responses:
        201:
          description: Estate created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
        400:
          description: Invalid value or format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /estate/{id}/tree:
    post:
      summary: Add a tree to an estate
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                x:
                  type: integer
                y:
                  type: integer
                height:
                  type: integer
      responses:
        201:
          description: Tree added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
        404:
          description: Estate not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        400:
          description: Invalid value or format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /estate/{id}/stats:
    get:
      summary: Get statistics of trees in an estate
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Tree statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  max:
                    type: integer
                  median:
                    type: integer
                  min:
                    type: integer
        404:
          description: Estate not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /estate/{id}/drone-plan:
    get:
      summary: Get the drone plan for an estate
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: max_distance
          in: query
          required: false
          schema:
            type: integer
      responses:
        200:
          description: Drone plan retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  distance:
                    type: integer
                  rest:
                    type: object
                    properties:
                      x:
                        type: integer
                      y:
                        type: integer
        400:
          description: Invalid max_distance value
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        404:
          description: Estate not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
