version: "3.9"
services:
  app:
    build: .
    container_name: sawittree
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=sawittree
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:latest
    container_name: sawittree
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sawittree
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
